In [1]:
"Hello World"

'Hello World'

In [2]:
import numpy as np

# numpy provides super-fast (c-backed) matrix operations
A = np.array([
    [1, 3, 2],
    [4, 5, 6],
    [7, 8, 9]
])

A

array([[1, 3, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A.T # Transpose

array([[1, 4, 7],
       [3, 5, 8],
       [2, 6, 9]])

In [4]:
np.linalg.inv(A.T) # Inverse

array([[-0.33333333,  0.66666667, -0.33333333],
       [-1.22222222, -0.55555556,  1.44444444],
       [ 0.88888889,  0.22222222, -0.77777778]])

In [10]:
import ipywidgets as ipy
import bqplot.pyplot as plt

@ipy.interact(x=(0, 10))
def hello(x):
    plt.figure()
    plt.plot(np.arange(0, x))
    plt.show()

interactive(children=(IntSlider(value=5, description='x', max=10), Output()), _dom_classes=('widget-interact',…